// Generated by delombok at Sun Jan 19 19:44:26 CET 2025
package com.game.engine.rendering;

import com.game.engine.msc.Debug;
import java.awt.*;

public class ShapeRender extends Renderer {
    private Color color = Color.darkGray;

    @Override
    public void start() {
        super.start();
        setVertices(new Rect(transform.getScale()));
    }

    @Override
    public void render(Graphics2D g) {
        if (transform.getParent() != null) {
            Rectangle r = new Rectangle((int) getPos().getX(), (int) getPos().getY(), (int) transform.getGlobalScale().getX(), (int) transform.getGlobalScale().getY());
        }
        //g.fill(r);
        Color colorBuffet = g.getColor();
        g.setColor(color);
        g.fill(getShape());
        g.setColor(colorBuffet);
    }



    public Color getColor() {
        return this.color;
    }



    public void setColor(final Color color) {
        this.color = color;
    }
}
