// Generated by delombok at Sun Jan 19 19:44:26 CET 2025
package com.game.engine.components;

import com.game.engine.GameEngine;
import com.game.engine.GameObject;
import com.game.engine.Scene;
import com.game.engine.msc.Debug;

/**
 * The component class is the base of the component system. The component can be inharited
 * where you can add your own logic to control the GameObjects.
 */
public abstract class Component {
    public Transform transform;
    private boolean started = false;

    public void start() {
        started = true;
    }

    public void update() {
    }

    public void __update__() {
    }

    public <T extends Component> T getComponent(Class<T> tClass) {
        return transform.getGameObject().getComponent(tClass);
    }

    public void instantiate(GameObject gameObject) {
        Scene selected = GameEngine.getSelectedScene();
        if (selected != null) {
            selected.getGameObjectHandler().getAddGameObject().add(gameObject);
        }
    }

    public GameObject instantiate(GameObject child, GameObject parent) {
        Scene selected = GameEngine.getSelectedScene();
        if (selected != null) {
            selected.getGameObjectHandler().getAddChildren().put(parent, child);
        }
        return child;
    }

    public void updateSecond() {
    }

    public void updateMillisecond() {
    }



    public boolean isStarted() {
        return this.started;
    }



    public void setStarted(final boolean started) {
        this.started = started;
    }
}
